# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Number-Phone-UK-DetailedLocations
version:      1.0
version_from: 
installdirs:  site
requires:
    DBM::Deep:                     0.97
    Number::Phone::UK:             1.52

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
